start:
  title: Sektionsmöte på Fysikteknologsektionen!
  logo:
css:
  main_color: "#8d0000"
  highlight_color: "rgba(252, 0, 0, 0.5)"
  hover_color: "#D20000"
  logo_color: "#000000"
  logo_size: 68px
