start:
  title: Sektionsmöte på Fysikteknologsektionen!
  logo: f
css:
  main_color: "#000000"
  highlight_color: "rgba(252, 0, 0, 0.5)"
  hover_color: "#D20000"
  logo_color: "#FFFFFF"
  logo_size: 68px
