# frozen_string_literal: true

Agenda.find_or_create_by!(position: 1, title: 'SOFMÖ - sektionsordförande förklarar mötet öppnat')
Agenda.find_or_create_by!(position: 2, title: 'Tid och sätt för mötet')
Agenda.find_or_create_by!(position: 3, title: 'Val av mötesordförande')
Agenda.find_or_create_by!(position: 4, title: 'Val av mötessekreterare')
Agenda.find_or_create_by!(position: 5, title: 'Val av justerare tillika rösträknare tillika omfamnare')
Agenda.find_or_create_by!(position: 6, title: 'Justering av röstlängden')
Agenda.find_or_create_by!(position: 7, title: 'Adjungeringar')
Agenda.find_or_create_by!(position: 8, title: 'Mötesinformation')
Agenda.find_or_create_by!(position: 9, title: 'Godkännande av föredragningslista')
Agenda.find_or_create_by!(position: 10, title: 'Meddelanden')
Agenda.find_or_create_by!(position: 11, title: 'Fullmäktigeval')
Agenda.find_or_create_by!(position: 12, title: 'Redovisning av ledningens preliminära verksamhetsberättelse för 2017')
Agenda.find_or_create_by!(position: 13, title: 'Motion angående reglementet 2.0')

prop = Agenda.find_or_create_by!(position: 14, title: 'Propositioner')
Bullet.find_or_create_by!(position: 1, agenda: prop, title: 'Proposition angående verksamhetsplan för 2018')
Bullet.find_or_create_by!(position: 2, agenda: prop, title: 'Proposition angående budget för 2018')
Bullet.find_or_create_by!(position: 3, agenda: prop, title: 'Proposition angående ändringar i stadgar - andra läsningen')
Bullet.find_or_create_by!(position: 4, agenda: prop, title: 'Proposition angående stadgeändringar')
Bullet.find_or_create_by!(position: 5, agenda: prop, title: 'Proposition angående sektionens värdegrund')
Bullet.find_or_create_by!(position: 6, agenda: prop, title: 'Proposition angående sektionsmötesordförande')
Bullet.find_or_create_by!(position: 7, agenda: prop, title: 'Proposition angående gratis sektionsblock för medlemmar')
Bullet.find_or_create_by!(position: 8, agenda: prop, title: 'Proposition angående tidsbegränsning av äskningar ur fonder')
Bullet.find_or_create_by!(position: 9, agenda: prop, title: 'Proposition angående ändringar i policy för funktionärsförmåner')
Bullet.find_or_create_by!(position: 10, agenda: prop, title: 'Proposition angående ändringar i policy för val')
Bullet.find_or_create_by!(position: 11, agenda: prop, title: 'Proposition angående förtydligande av val av Årets lärare')

motioner = Agenda.find_or_create_by!(position: 15, title: 'Motioner')
Bullet.find_or_create_by!(position: 1, agenda: motioner, title: 'Motion angående sektionsmerch')
Bullet.find_or_create_by!(position: 2, agenda: motioner, title: 'Motion angående slushmaskin')
Bullet.find_or_create_by!(position: 3, agenda: motioner, title: 'Motion angående kassasystem och izettle')
Bullet.find_or_create_by!(position: 4, agenda: motioner, title: 'Motion angående älgstaty')
Bullet.find_or_create_by!(position: 5, agenda: motioner, title: 'Motion angående gungstolar')
Bullet.find_or_create_by!(position: 6, agenda: motioner, title: 'Motion angående sektionsmormor')
Bullet.find_or_create_by!(position: 7, agenda: motioner, title: 'Motion angående tv')
Bullet.find_or_create_by!(position: 8, agenda: motioner, title: 'Motion angående bakisar')

funk = Agenda.find_or_create_by!(position: 16, title: 'Funktionärsval')
Bullet.find_or_create_by!(position: 1, agenda: funk, title: 'Sektionsordförande')
Bullet.find_or_create_by!(position: 2, agenda: funk, title: 'Sekreterare')
Bullet.find_or_create_by!(position: 3, agenda: funk, title: 'Kassör')
Bullet.find_or_create_by!(position: 4, agenda: funk, title: 'Överfös')
Bullet.find_or_create_by!(position: 5, agenda: funk, title: 'Sanningsminister')
Bullet.find_or_create_by!(position: 6, agenda: funk, title: 'Kulturminister')
Bullet.find_or_create_by!(position: 7, agenda: funk, title: 'Sexmästare')
Bullet.find_or_create_by!(position: 8, agenda: funk, title: 'Vice cafémästare')
Bullet.find_or_create_by!(position: 9, agenda: funk, title: 'Näringslivsansvarig')
Bullet.find_or_create_by!(position: 10, agenda: funk, title: 'Likabehandlingsordförande')
Bullet.find_or_create_by!(position: 11, agenda: funk, title: 'Revisor')
Bullet.find_or_create_by!(position: 12, agenda: funk, title: 'Revisorssuppleant')
Bullet.find_or_create_by!(position: 13, agenda: funk, title: 'Köksmästare')
Bullet.find_or_create_by!(position: 14, agenda: funk, title: 'Hofmästare')
Bullet.find_or_create_by!(position: 15, agenda: funk, title: 'Pubmästare')
Bullet.find_or_create_by!(position: 16, agenda: funk, title: 'Idrottsförman')
Bullet.find_or_create_by!(position: 17, agenda: funk, title: 'Reisemeister')
Bullet.find_or_create_by!(position: 18, agenda: funk, title: 'Vice kassör med sexmästeriansvar')
Bullet.find_or_create_by!(position: 19, agenda: funk, title: 'Vice kassör med nollningsansvar')
Bullet.find_or_create_by!(position: 20, agenda: funk, title: 'Sektionshärold')
Bullet.find_or_create_by!(position: 21, agenda: funk, title: 'Sångarstridsförman')
Bullet.find_or_create_by!(position: 22, agenda: funk, title: 'Vice näringslivsansvarig')
Bullet.find_or_create_by!(position: 23, agenda: funk, title: 'Von tänen-redaktör')

Agenda.find_or_create_by!(position: 17, title: 'Övriga frågor')
Agenda.find_or_create_by!(position: 18, title: 'Frågan om F:s förträfflighet')
Agenda.find_or_create_by!(position: 19, title: 'Mötesordförandes fräckis')
Agenda.find_or_create_by!(position: 20, title: 'MOFMA - mötesordförande förklarar mötet avslutat')
